{% set name = "aisim" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aisim-{{ version }}.tar.gz
  sha256: f907ea2cad5fd25fab81942af2fb9d8b6b25c065e0513c2d3634bb85495cf5d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - matplotlib-base
    - numpy
    - python >=3.4
    - scipy

test:
  imports:
    - aisim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bleykauf/aisim
  summary: Simulations for light-pulse atom interferometry
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://aisim.readthedocs.io/
  dev_url: https://github.com/bleykauf/aisim

extra:
  recipe-maintainers:
    - bleykauf
