{% set name = "aisim" %}
{% set version = "0.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aisim-{{ version }}.tar.gz
  sha256: 186eec572f233fb0f7eed3a491f90388fb01acb840da26e0450117035d24c340

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - matplotlib-base
    - numpy
    - python >=3.4
    - scipy

test:
  imports:
    - aisim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bleykauf/aisim
  summary: Simulations for light-pulse atom interferometry
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://aisim.readthedocs.io/
  dev_url: https://github.com/bleykauf/aisim

extra:
  recipe-maintainers:
    - bleykauf
