{% set name = "aisim" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aisim-{{ version }}.tar.gz
  sha256: b62d6576e3fc7ca338f5ba6fc583ee534e82a3163da648a3dffe8b97fc9cf6c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - matplotlib-base
    - numpy
    - python >=3.4
    - scipy

test:
  imports:
    - aisim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bleykauf/aisim
  summary: Simulations for light-pulse atom interferometry
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://aisim.readthedocs.io/
  dev_url: https://github.com/bleykauf/aisim

extra:
  recipe-maintainers:
    - bleykauf
